config/routes.rb
Rails.application.routes.draw do

  resources :users do
    get :get_events, on: :collection
    member do
      get :following, :followers, :feed, :settings, :membre_de, :fichiers_utilisateur, :taches_attribuees, :messages_utilisateur
    end
  end
  
  resources :projects do       
    member do
      get :members
      get :remove_member     
      post :add_member
    end
  end
  
  resources :datafiles do
    member do
      get :download, :delete_file, :versions_fichier
    end
  end
  
  resources :versions do
    member do
      get :download
    end
  end
  
  resources :contacts do
    get :autocomplete_contact_nom, :on => :collection
  end
  
  resources :tasks do
    member do
      get :charges
      get :remove_member     
      post :add_member
    end
  end
  
  resources :messages
  resources :relationships
  resources :sessions, :only => [:new, :create, :destroy] 
  resources :microposts, :only => [:create, :destroy]
    
    
  root :to => 'pages#acceuil'  
  get '/administration', :to => 'pages#administration'
  get '/signup',  :to => 'pages#inscription'
  get '/signin',  :to => 'sessions#create'
  get '/projet', :to => 'pages#projet'
  get '/calendrier', :to => 'pages#calendrier'
  get '/ged', :to => 'pages#ged'
  delete '/signout', :to => 'sessions#destroy'
  post "/projects/add_member", :to => 'projects#add_member'
  get "/projects/remove_member", :to => 'projects#remove_member'
  post "/tasks/add_member", :to => 'tasks#add_member'
  get "/tasks/remove_member", :to => 'tasks#remove_member'
  









end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  login              :string
#  encrypted_password :string
#  salt               :string
#  admin              :boolean
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class User < ActiveRecord::Base
  
  has_one :contact
  
  has_many :projects 
  
  has_many :project_user_relations, :foreign_key => :membre_id,
                                    :dependent => :destroy
  has_many :membre_de, :through => :project_user_relations, :source => :projet
  
  has_many :tasks
  
  has_many :task_user_relations, :foreign_key => :user_id,
                                    :dependent => :destroy
                                    
  has_many :charge_de, :through => :task_user_relations, :source => :task
  
  has_many :microposts, :dependent => :destroy
  
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  has_many :datafiles, :dependent => :destroy
  
  has_many :messages, :foreign_key => "id_source",:dependent => :destroy
  
  has_many :reverse_messages, :foreign_key => "id_destination",
                                   :class_name => "Message",
                                   :dependent => :destroy
  
  has_many :sent_messages, :through => :messages, :source => :emetteur
  
  has_many :received_messages, :through => :messages, :source => :destinataire
  
  has_many :connexions, :dependent => :destroy
  
  
  attr_accessor :password

  
  validates :login,  :presence => true,
                     :length   => { :maximum => 20 },
                     :uniqueness => { :case_sensitive => false } 
                   
          
                    
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }                                            
                       
  before_save :encrypt_password
  
  
  
    def has_password?(password_soumis)
      encrypted_password == encrypt(password_soumis)
    end
    
    def self.authenticate(login, submitted_password)
      user = find_by_login(login)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
    end
    
    def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
    
    def feed
      Micropost.from_users_followed_by(self)
    end
    
    def following?(followed)
      relationships.find_by_followed_id(followed)
    end
  
    def follow!(followed)
      relationships.create!(:followed_id => followed.id)
    end
    
    def unfollow!(followed)
      relationships.find_by_followed_id(followed).destroy
    end
     
    def membre_de?(project)
       project_user_relations.find_by(:projet_id => project.id)
    end
     
    def ajouter_au_projet!(projet)
       project_user_relations.create!(:projet_id => projet.id)
    end
     
     
    def retirer_du_projet!(projet)
       project_user_relations.find_by(:projet_id => projet.id).destroy
    end
    
    def charge_de?(task)
       task_user_relations.find_by(:task_id => task.id)
    end
    
    def attribuer_tache!(task)
       task_user_relations.create!(:task_id => task.id)
    end
     
     
    def retirer_tache!(task)
       task_user_relations.find_by(:task_id => task.id).destroy
    end
    
    def nouveau_message!(destinataire,message)
      messages.create!(:id_destination => destinataire.id,:content => message)
    end
    
    def derniere_connexion(time_distance=false)
        
        t = connexions.first.finish 
        
        if time_distance
          t = Time.current-t
        end
        
        t
        
    end
    
    def en_ligne?(clientxmpp)
      
       #clientxmpp.get_user_activity(self)
       clientxmpp.discovery(self.login)
      
    end
    
    def last_activity(clientxmpp,current_user)
    
        if current_user == self
          
            clientxmpp.current_user_last_activity
          
        else
          
            clientxmpp.activity(self.login)       
            
        end      
 
    end
    

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.current}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA512.hexdigest(string)
    end
                    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :verify_connection, :except => [:create]
  before_filter :not_idle, :except => [:index]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => [:index, :destroy]
    
  def index
    
      @user = User.new
      @users = User.all      
      
      #@roster = clientxmpp.roster
      
      if(@users.empty? == false)
      
        clientxmpp.get_activities(@users) 
      
      end   
      
      @titre = "Tous les utilisateurs"
      @id = "users"

  end
  
  def following   
     
      if(params[:sidemenu]!=nil)       
        
          Thread.new do 
             
                begin 
                  
                  @user = User.find(params[:id])    
                  @users = @user.following
                  
                  
                  @users.sort_by{|e| e.contact.organization.id }
                
                  if(@users.empty? == false)
                    
                    clientxmpp.get_activities(@users) 
                    
                 end 
  
                  @cu_roster = @users
          
                  @cu_roster.sort_by{|e| e.last_activity(@clientxmpp,@current_user)}
                  
                  render 'index_sidemenu'
                      
                rescue Exception => e  
                    puts e.message  
                    #puts e.backtrace.inspect      
                end   
              
           end       
            
      else
        
          @user = User.find(params[:id])    
          @users = @user.following
          
          
          @users.sort_by{|e| e.contact.organization.id }
        
          if(@users.empty? == false)
            
            clientxmpp.get_activities(@users) 
            
          end 
          @titre = "Contacts de #{@user.contact.nom_complet}"
          @id = "user_followings"
        
          render 'index'
      
      end   
    
    
  end
  
  def show
    @user = User.find(params[:id])
    @titre = @user.contact.nom_complet
  end

  def new
    @user=User.new   
  end
  
  def create
  
    begin
         @user = User.new(user_params) 
         @user.save!
         @user.contact=Organization.create!(:nom => "Nom organisation").contacts.create!            
         Datadirectory.new_user(@user)          
         flash[:success] = "Le compte a été correctement créé."  
         
    rescue Exception => e  
         @user.delete
         puts e.message  
         puts e.backtrace.inspect 
         flash[:error] = e.message
    
    end
    
    redirect_to :back  

  end
  
  def edit
    @titre = "Édition compte"
    @user = User.find(params[:id])
  end
  
  def update   
    @user = User.find(params[:id])
    @titre = "Édition profil"
    if @user.update_attributes(user_params)
      flash[:success] = "Profil actualisé."
      redirect_to 'edit'      
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    
    if @user!=current_user && @user.en_ligne?(current_user)
      if@user.destroy
        flash[:success] = "Utilisateur supprimé."
        redirect_to users_path
      else
        render users_path
      end
    else
      flash[:error] = "Vous ne pouvez pas supprimer ce compte tant qu'il est connecté."
      redirect_to users_path
    end
  end
  
  

  def followers   
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    @titre = "Abonnés"
    render 'show_follow'
  end
  
  def feed
    @feed_items = current_user.feed.paginate(:page => params[:page])
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
    @microposts == nil  ?  @micropost = Microposts.new :  
    @titre = "Publications de #{@user.contact.nom_complet}"
    render 'show_feeds'
  end
  
  def settings
    @user = User.find(params[:id])
    @titre = "Paramètres de #{@user.contact.nom_complet}"
  end
  
  def membre_de
      
    @user = User.find(params[:id])

    redirect_to :controller => 'projects', :action => 'index', :id => @user.id
    
  end
  
  def taches_attribuees
    @user = User.find(params[:id])
    @tasks = @user.charge_de.paginate(:page => params[:page])   
    @tasks.first == nil ?  @task = Task.new :   
    @titre = "Tâches attribuées à #{@user.contact.nom_complet}"
    render '/tasks/index'
  end
  
  def fichiers_utilisateur
   
    @user = User.find(params[:id])
     
    redirect_to :controller => 'datafiles', :action => 'index', :user_id => @user.id
  end
  
  def messages_utilisateur
   
    @user = User.find(params[:id])

    redirect_to :controller => 'messages', :action => 'index', :id => @user.id
    
              
   end
   
   
   def get_events
    
    @projects = current_user.membre_de
    events = []
    @projects.each do |project|
      events << {:id => project.id, :title => "#{project.nom}", :start => "#{project.datedebut}",:end => "#{project.datefin}" }
    end
    
    respond_to do |format|
        format.html { redirect_to :back }
        format.json   { render :text => events.to_json }
    end
  end
  

private

  def user_params
      params.require(:user).permit(:nom, :login, :password, :password_confirmation)
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to('/') unless current_user?(@user)
  end
  

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% user ||= current_user %>	

					<div class="col-lg-4 col-sm-7">
						<div class="user" id="<%= user.id.to_i %>" >
						
							<div class="member">
									<div class="user-avatar">									
											<%= image_tag("team_pic2.jpg", :width => "50px", :height => "50px",:alt => "Team Member", :class => "img-circle") %>
										</div><!-- /.author-avatar -->		
																									
										
										<div class="user-details">																			
											
											<div class="member-top">		
												
												<%= render 'shared/palette_admin', :object => user %>	
																	
												<h4 class="name">												
													<%= link_to user.contact.nom_complet, user.contact %>																										
												</h4>
										
												<% if user.en_ligne?(@clientxmpp) %>
												
													<p class="online"> En ligne </p>												
													
												
												<% else %>
												
													<p class="offline"> Hors ligne </p>	
											
												<% end %>
												
												<% if user.last_activity(@clientxmpp,current_user)!=nil  %>
													
															<p>Actif il y a <%= time_ago_in_words(user.last_activity(@clientxmpp,@current_user).seconds.ago) %></p>
													
												<% end %>
												
												<!--
																		
												<% if user == current_user %>
													
													
													<p>Presence :<%=  @clientxmpp.presence %></p>
												    
												    		
												<% else %>	
				
													
													<% if @roster!= nil%>
																
														Presence :<%=  @roster[Clientxmpp.jid(user)].presence %>
													
				
													<% end %>
																
												<% end %>
												
												-->
																
				
												<% unless user.connexions.empty? %>
												
												<p> Dernière connexion : <%= user.derniere_connexion.to_formatted_s(:normal) %>	</p>
												
												<% end %>									
																																	
												<p><a href="<%= feed_user_path(user) %>"><%= pluralize(user.microposts.count, "Publication") %></a> | <a href="<%= following_user_path(user) %>"><%= pluralize(user.following.count, "Contact") %><!-- </a> | <a id="Abonne" href="<%= followers_user_path(user) %>"><%= pluralize(user.followers.count, "Abonné") %></a> --> </p> 
												<p><a href="<%= membre_de_user_path(user) %>"><%= pluralize(user.membre_de.count, "Projet") %></a> | <a href="<%= taches_attribuees_user_path(user) %>"><%= pluralize(user.charge_de.count, "Tâches") %></a> | <a href="<%= fichiers_utilisateur_user_path(user) %>"><%= pluralize(user.datafiles.count, "Fichier") %></a> </p> 											 
												
											</div><!-- /.member-top -->
											
											<% @user = user %>
											
											<%= render '/shared/message_button_form'%>
											
											<%= render '/shared/follow_form'%>
											
											
											
											
												
											
										</div><!-- /.member-details -->

							</div><!-- /.member -->
				</div>
		 </div>

app/views/users/edit.html.erb

<section id="aboutUs">
		
<div class="inner_wrapper">

	
  <div class="container">
  	
  	<%= render 'shared/messages', :object => @user %>
  	
    <div class="inner_section">
    	
		<div class="col-lg-6 col-sm-7">
			
			<h2>Informations du compte :</h2>
	
					<%= form_for(@user) do |f| %>
			
					    <%= f.label :login, "Login", :class => "label" %><br />
					    <%= f.text_field :login, :class => "input-text" %>
		
				
					    <%= f.label :password, "Nouveau mot de passe", :class => "label" %><br />
					    <%= f.password_field :password, :class => "input-text" %>

					    <%= f.label :password_confirmation, "Confirmation du nouveau mot de passe", :class => "label" %><br />
					    <%= f.password_field :password_confirmation, :class => "input-text" %>

					    <%= f.submit "Modifier", :class => "input-btn" %>

					<% end %>
	       
	        
	    </div>


    
    </div>
  </div> 
  </div>
</section>


app/views/users/index.html.erb
<%= render 'menu_action', :object => @users.first || @user %>

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
		<div class="member-area">
						
			
					<div id ="<%= @id %>" class="row">		
										
						  <% unless @users.empty? %>				
					        
					        	<%= render @users %>
					        
					      <%else%>
					      
					     	<div class="col-lg-6 col-sm-7">
					        	<p>Aucun utilisateur.</p>
					        </div>
					        
					      <% end %>
					     
						
						
					</div><!-- /.row -->
		</div>
</div>
</section>


app/views/users/index.js.erb
$('#users').html("<%= escape_javascript(render @users) %>")

app/views/users/index_sidemenu.js.erb

<% unless @current_user.following == nil || @current_user.following.empty? %>

$('#users_sidemenu').html("<%= escape_javascript(render 'layouts/side_menu_users') %>")

<% else %>

$('#users_sidemenu').html("<ul><li><span>Aucun contact</span></li></ul>")
	
						
<% end %>

app/views/users/new.html.erb
<%= render 'menu_action', :object => @user %>

<section id="aboutUs">
		
<div class="inner_wrapper">

	
  <div class="container">
  	
    <div class="inner_section">
    	
		<div class="col-lg-6 col-sm-7">
			
			<h2><%= @titre %></h2>
	
					<div class="form">
		        		<%= form_for(@user) do |f| %>       		
		        		
							<%= f.label :login, "Login", :class => "label" %><br />
							<%= f.text_field :login, :class => "input-text", :onFocus => "if(this.value==this.defaultValue)this.value='';", :onBlur =>"if(this.value=='')this.value=this.defaultValue;" %>
		
							<%= f.label :password, "Mot de passe", :class => "label" %><br />
							<%= f.password_field :password, :class => "input-text", :onFocus => "if(this.value==this.defaultValue)this.value='';", :onBlur =>"if(this.value=='')this.value=this.defaultValue;" %>
		
							<%= f.label :password_confirmation, "Confirmation", :class => "label" %><br />
							<%= f.password_field :password_confirmation, :class => "input-text", :onFocus => "if(this.value==this.defaultValue)this.value='';", :onBlur =>"if(this.value=='')this.value=this.defaultValue;" %>
		
							<%= f.submit "Créer", :class => "input-btn" %>
							
						<% end %>
			          </div>
	       
	        
	    </div>
 
    </div>
  </div> 
  </div>
</section>


app/views/users/settings.html.erb

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
	<div class="member-area">
		<div class="row">
			<%= render 'user'%>
			<%= link_to "Modifier", edit_contact_path(current_user.contact) %>			
						
		</div><!-- /.row -->
	</div>
</div>
</section>


app/views/users/show.html.erb

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
	<div class="member-area">
		<div class="row">
			<%= render @user %>									
		</div><!-- /.row -->
	</div>
</div>
</section>
