config/routes.rb
Rails.application.routes.draw do

  resources :users do
    get :get_events, on: :collection
    member do
      get :following, :followers, :feed, :settings, :membre_de, :fichiers_utilisateur, :taches_attribuees, :messages_utilisateur
    end
  end
  
  resources :projects do       
    member do
      get :members
      get :remove_member     
      post :add_member
    end
  end
  
  resources :datafiles do
    member do
      get :download, :delete_file, :versions_fichier
    end
  end
  
  resources :versions do
    member do
      get :download
    end
  end
  
  resources :contacts do
    get :autocomplete_contact_nom, :on => :collection
  end
  
  resources :tasks do
    member do
      get :charges
      get :remove_member     
      post :add_member
    end
  end
  
  resources :messages
  resources :relationships
  resources :sessions, :only => [:new, :create, :destroy] 
  resources :microposts, :only => [:create, :destroy]
    
    
  root :to => 'pages#acceuil'  
  get '/administration', :to => 'pages#administration'
  get '/signup',  :to => 'pages#inscription'
  get '/signin',  :to => 'sessions#create'
  get '/projet', :to => 'pages#projet'
  get '/calendrier', :to => 'pages#calendrier'
  get '/ged', :to => 'pages#ged'
  delete '/signout', :to => 'sessions#destroy'
  post "/projects/add_member", :to => 'projects#add_member'
  get "/projects/remove_member", :to => 'projects#remove_member'
  post "/tasks/add_member", :to => 'tasks#add_member'
  get "/tasks/remove_member", :to => 'tasks#remove_member'
  









end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="col-lg-10 col-sm-7">
  <div class="error_box">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete } do |f| %>
	  <%= f.submit "Retirer", :class => "input-btn2" %>
	<% end %>
  <% else %>
    <%= form_for current_user.relationships.build(:followed_id => @user.id) do |f| %>
	  <%= f.hidden_field :followed_id %>
	  <%= f.submit "Ajouter", :class => "input-btn2" %>
	<% end %>
  <% end %>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
   
    <div class="col-lg-6 col-sm-7">
    	
        <div class="top_left_cont"> 
        	
        	<div class="form">
        		
        		<%= form_for(:session, :url => sessions_path) do |f| %>
        		
				    <%= f.label :login, "Login", :class => "label" %><br />
				    <%= f.text_field :login, :class => "input-text", :style => "width: 100%;", :onFocus => "if(this.value==this.defaultValue)this.value='';", :onBlur =>"if(this.value=='')this.value=this.defaultValue;", :required => true %>

				    <%= f.label :password, "Mot de passe", :class => "label" %><br />
				    <%= f.password_field :password, :class => "input-text", :style => "width: 100%;",:onFocus => "if(this.value==this.defaultValue)this.value='';", :onBlur =>"if(this.value=='')this.value=this.defaultValue;", :required => true %>

				    <%= f.submit "S'identifier", :class => "input-btn" %>
				    
				  	<%= render 'shared/messages', :object => f.object %>  
				    
				<% end %>
				
				
				
	          </div>
	          
	          
        	      	        
        </div>
        
    </div>

app/views/shared/_message_button_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">

    <%= form_tag new_message_path, :method => :get do %>
	  <%= hidden_field_tag :user, @user.id %>
	  <%= submit_tag "Message", :class => "input-btn2" %>
	<% end %>

  </div>
<% end %>

app/views/shared/_message_form.html.erb
<%= form_for @message, :remote => true do |f| %> 
	<%= hidden_field_tag :user, @user.id %>
    <%= f.text_area :content, :class => "input-text text-area", :placeholder => "Message a envoyer . . .", :maxlength => "200", :required => true %>
    <%= f.submit "Envoyer", :class => "input-btn" %>
<% end %>


app/views/shared/_messages.html.erb

<% if !object.nil? && object.respond_to?(:errors) && object.errors.any? %>
<div class="col-lg-12 col-sm-7">
  <div class="error_box">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>
<% if flash[:warning] %>
<div class="col-lg-12 col-sm-7">
  <div class="warning_box">
    <%= flash[:warning] %>
  </div>
</div>
<% end %>
<% if flash[:error] %>
<div class="col-lg-12 col-sm-7">
  <div class="error_box">
    <%= flash[:error] %>
  </div>
</div>
<% end %>
<% if flash[:success] %>
<div class="col-lg-12 col-sm-7">
  <div class="success_box">
    <%= flash[:success] %>
  </div>
</div>
<% end %>


app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %> 
    <%= f.text_area :content, :class => "input-text text-area", :style => "width: 100%;", :placeholder => "Laissez une publication que tout vos abonnés pourront voir . . .", :required => true %>
    <%= f.submit "Publier", :class => "input-btn" %>
<% end %>


app/views/shared/_palette_admin.html.erb
<% if current_user.admin? %>

        <div id="palette_admin">
  	
        	   <% if object.class.to_s == "User" %>
        	   		<% if @project != nil %>
        	 			<%= link_to "Retirer", "/projects/#{@project.id}/remove_member?user_id=#{object.id}", :remote => true %> |
        	 		<% end %>
					<%= link_to "Modifier", "/contacts/#{object.contact.id}/edit" %> 
			   <% else %>
					<%= link_to "Modifier", "/#{object.class.to_s.downcase}s/#{object.id}/edit" %>
			   <% end %>
        	
        		|
                          
              <%= link_to "Supprimer", object, :method => :delete, :confirm => "Etes-vous certain ?" %>
        </div>   
                       
<% end %>