config/routes.rb
Rails.application.routes.draw do

  resources :users do
    get :get_events, on: :collection
    member do
      get :following, :followers, :feed, :settings, :membre_de, :fichiers_utilisateur, :taches_attribuees, :messages_utilisateur
    end
  end
  
  resources :projects do       
    member do
      get :members
      get :remove_member     
      post :add_member
    end
  end
  
  resources :datafiles do
    member do
      get :download, :delete_file, :versions_fichier
    end
  end
  
  resources :versions do
    member do
      get :download
    end
  end
  
  resources :contacts do
    get :autocomplete_contact_nom, :on => :collection
  end
  
  resources :tasks do
    member do
      get :charges
      get :remove_member     
      post :add_member
    end
  end
  
  resources :messages
  resources :relationships
  resources :sessions, :only => [:new, :create, :destroy] 
  resources :microposts, :only => [:create, :destroy]
    
    
  root :to => 'pages#acceuil'  
  get '/administration', :to => 'pages#administration'
  get '/signup',  :to => 'pages#inscription'
  get '/signin',  :to => 'sessions#create'
  get '/projet', :to => 'pages#projet'
  get '/calendrier', :to => 'pages#calendrier'
  get '/ged', :to => 'pages#ged'
  delete '/signout', :to => 'sessions#destroy'
  post "/projects/add_member", :to => 'projects#add_member'
  get "/projects/remove_member", :to => 'projects#remove_member'
  post "/tasks/add_member", :to => 'tasks#add_member'
  get "/tasks/remove_member", :to => 'tasks#remove_member'
  









end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_datafile_info.html.erb

<tr>
		<td><%= @datafile.nom %></td>
		<td><%= @datafile.version %></td>
		<td><%= @datafile.description %></td>
		<td><%= @datafile.user.contact.nom_complet %></td>
		<td><%= @datafile.created_at.to_formatted_s(:normal) %></td>				
		<td><%= link_to "Versions", versions_fichier_datafile_path(:id =>@datafile.id, :fichier_id =>@datafile.fichier_id) %></td>		
		<td><%= link_to "Ajouter une version", new_datafile_path(:id =>@datafile.id,  :fichier_id =>@datafile.fichier_id) %></td>
		<td><%= link_to "Télécharger", download_datafile_path(@datafile.id) %></td>
		
</tr>


<!-- link_to pluralize(@datafile.versions.count , "version"), "#{versions_path}?id=#{@datafile.id}" # %> -->
<!-- # link_to "Télécharger", download_version_path(@datafile.versions.first) %> -->
<!-- # link_to "Supprimer", @datafile, :method => :delete %> -->

app/views/application/_file_info.html.erb

<tr>
		<td><%= @file["name"] %></td>
		<td><%= @file["created_at"] %></td>
		<td><%= @file["updated_at"] %></td>
		<td><%= @file["permissions"] %></td>
		<td></td>
		<td><%= link_to "Télécharger", "#" %></td>
		<td><%= link_to "Supprimer", datafiles_path(:file_path => @file["absolute_path"]), :method => :delete_file %></td>
</tr>

app/views/application/_menu_action.html.erb
  
<!-- Portfolio -->
<section id="menu_action"> 
  
  <!-- Container -->
  <div class="container portfolio_title"> 
    	
  	<!-- Title -->
    <div class="section-title">
      <h1><%= @titre %></h1>
    </div>
    <!--/Title -->  	

	
	<%= render 'shared/messages', :object => object %>
	
	<ul id="views">
			<h5>
				<li>
					<a id="kanban_btn" class="<% if @vue="kanban" %>action_active<% end %> action" href="#">Kanban</a>							
				</li>
				<li>
					<a id="table_btn" class="<% if @vue="tableau" %>action_active<% end %> action" href="#">Tableau</a>							
				</li>
				<li>
					<a id="calendar_btn" class="<% if @vue="calendrier" %>action_active<% end %> action" href="#">Calendrier</a>							
				</li>
				<li>
					<a id="gannt_btn" class="<% if @vue="gantt" %>action_active<% end %> action" href="#">Gantt</a>							
				</li>
									
			</h5>
								
	</ul>
	
	<ul class="clearfix">
			<h5>
				<li>
					<a class="action" href="<%= "/#{object.class.to_s.downcase}s/new" %>">Ajouter</a>							
				</li>
									
			</h5>
								
	</ul>
	
	
    
    
    
    
  </div>
  <!-- Container -->


  
</section>

app/views/application/_project_info.html.erb
	<div class="portfolio-item one-four isotope-item <%= @project.etat.delete(' ') %>">
        <div class="portfolio_img" style="opacity: 0;"> <img> </div>
        <div class="item_overlay">
          <div class="item_info"> 
          	
            <h4 class="project_name"><%= link_to @project.nom , @project %></h4>
      		  
      		<p>Etat : <%= @project.etat %></p>    
      		      		
      		<p>Date de début : <%= @project.datedebut.to_formatted_s(:date) %></p>
      		
      		<p>Date de fin : <%= @project.datefin.to_formatted_s(:date) %></p>
      		
         	<p>Responsable : <%= @project.user.contact.nom_complet %></p>
         	
         	<p><a href="<%=  members_project_path(@project) %>"><%= pluralize(@project.membres.count, "Membre") %></a>
         	
		 	| <a href="#">0 Tâches</a> | <a href="#">0 Fichiers</a></p>
         	
         	<%= render 'shared/palette_admin', :object => @project %>
         	
         	
          </div>
        </div>
      </div>
						

app/views/application/_task_info.html.erb
	<div class="portfolio-item one-four isotope-item <%= @task.etat.delete(' ') %>">
        <div class="portfolio_img" style="opacity: 0;"> <img> </div>
        <div class="item_overlay">
          <div class="item_info"> 
          	
            <h4 class="task_name"><%= link_to @task.nom , @task %></h4>
      		  
      		<p>Etat : <%= @task.etat %></p>    
      		      		
      		<p>Date de début : <%= @task.datedebut.to_formatted_s(:date) %></p>
      		
      		<p>Date de fin : <%= @task.datefin.to_formatted_s(:date) %></p>
         	
         	<p><a href="<%=  charges_task_path(@task) %>"><%= pluralize(@task.charges.count,"Chargé de la tâche","Chargés de la tâche") %></a>
         	
         	<%= render 'shared/palette_admin', :object => @task %>
         	
         	
          </div>
        </div>
      </div>
						

app/views/application/_version_info.html.erb

<tr>
		<td><%= @datafile.nom %></td>
		<td><%= @datafile.version %></td>
		<td><%= @datafile.description %></td>
		<td><%= @datafile.user.contact.nom_complet %></td>
		<td><%= @datafile.created_at %></td>
		<td><%= link_to "Télécharger", download_datafile_path(:id => @datafile.id) %></td>
		<td><%= link_to "Supprimer", delete_file_datafile_path(:id => @datafile.id, :fichier_id => @datafile.fichier_id ) %></td>
</tr>

app/views/application/show_feeds.html.erb
<%= render 'menu_action', :object => @microposts.first || @micropost %>

<section id="aboutUs">
		
<div class="inner_wrapper">

	
  <div class="container">


   		 <div class="inner_section">  		 	    		
	     
				<div class="col-lg-12 col-sm-7">
					<%= pluralize(@user.microposts.count, "Publication") %>
					
						<% unless @user.microposts.empty? %>
					        <table>
					         	<%= render @microposts %>				         	
					        </table>
				 			<%= will_paginate @microposts %>				 		
				 		
		 				<% end %>
				</div>	
				        
	
	        
	    </div>

    </div>
  </div> 
  </div>
</section>

app/views/application/show_files.html.erb
<%= render 'menu_action', :object => @datafiles.first || @datafile %>

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
		<div class="member-area">
			
			
					<div class="row">
				
							<ul class="clearfix">
								<h5>
									<li>
										<a class="lel" href="<%= new_datafile_path %>">Ajouter</a>							
									</li>
									
								</h5>
								
							</ul>
							<div id="filters" class="sixteen columns">
							
							 <ul class="clearfix">
	
	      	
						        <li><a id="all" href="#" data-filter="*" class="active">
						          <h5>Tout</h5>
						          </a></li>
						          
						        <li><a class="" href="#" data-filter=".Nouveau">
						          <h5>Documents</h5>
						        </a></li>
						        
						        <li><a class="" href="#" data-filter=".Encours">
						          <h5>Fichiers</h5>
						        </a></li>
					          
					
					  	    </ul>
					      
					      </div>
																	
						<div class="col-lg-12 col-sm-7">
							
								
								<% unless @datafiles.empty? %>
	
										<table class="table">
																		
											<tr>												
												<td>Nom</td>
												<td>Dernière version</td>
												<td>Ajouté par</td>
												<td>Date et heure d'ajout</td>
												<td>Historique</td>
												<td>Téléchargement</td>
												<td></td>
											</tr>
											
											
									        <% @datafiles.each do |datafile| %>
									        
										 		  <% @datafile = datafile %>
									 		  
												  <%= render "datafile_info" %>
												  
												  <%= will_paginate @datafiles %>			          
									          
								    	    <% end %>							    	    
								    	    
								    	</table>
						    	   
						        
							    <% else %>
							        	<p>Aucun fichier.</p>							       				        				    
								<% end %>
								
						 </div>
						
					</div><!-- /.row -->
		</div>
</div>
</section>


app/views/application/show_users.html.erb
<%= render 'menu_action', :object => @users.first || @user %>

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
		<div class="member-area">
			
					<div id ="users" data-user ="<%= current_user.id %>" class="row">						
						
						  <% unless @users.empty? %>				
					        
					        	<%= render @users %>
					        
					      <%else%>
					      
					     	<div class="col-lg-6 col-sm-7">
					        	<p>Aucun utilisateur.</p>
					        </div>
					        
					      <% end %>
					     
						
						
					</div><!-- /.row -->
		</div>
</div>
</section>


app/views/application/show_versions.html.erb
<%= render 'menu_action', :object =>  @datafile %>

<section class="page_section team" id="team"><!--main-section team-start-->
  <div class="container">
		<div class="member-area">
			
			
					<div class="row">
								
																	
						<div class="col-lg-12 col-sm-7">
							
								
								<% unless @datafiles.empty? %>
	
										<table class="table">
																		
											<tr>
												<td>Nom</td>												
												<td>Version</td>
												<td>Description</td>
												<td>Ajouté par</td>
												<td>Date et heure d'ajout</td>
												<td>Téléchargement</td>
												<td></td>
											</tr>
											
											
									        <% @datafiles.each do |datafile | %>
									        
										 		  <% @datafile = datafile %>
									 		  
												  <%= render "version_info" %>		          
									          
								    	    <% end %>							    	    
								    	    
								    	</table>
						    	   
						        
							    <% else %>
							        	<p>Aucune version.</p>							       				        				    
								<% end %>
								
						 </div>
						
					</div><!-- /.row -->
		</div>
</div>
</section>
