config/routes.rb
Rails.application.routes.draw do

  resources :users do
    get :get_events, on: :collection
    member do
      get :following, :followers, :feed, :settings, :membre_de, :fichiers_utilisateur, :taches_attribuees, :messages_utilisateur
    end
  end
  
  resources :projects do       
    member do
      get :members
      get :remove_member     
      post :add_member
    end
  end
  
  resources :datafiles do
    member do
      get :download, :delete_file, :versions_fichier
    end
  end
  
  resources :versions do
    member do
      get :download
    end
  end
  
  resources :contacts do
    get :autocomplete_contact_nom, :on => :collection
  end
  
  resources :tasks do
    member do
      get :charges
      get :remove_member     
      post :add_member
    end
  end
  
  resources :messages
  resources :relationships
  resources :sessions, :only => [:new, :create, :destroy] 
  resources :microposts, :only => [:create, :destroy]
    
    
  root :to => 'pages#acceuil'  
  get '/administration', :to => 'pages#administration'
  get '/signup',  :to => 'pages#inscription'
  get '/signin',  :to => 'sessions#create'
  get '/projet', :to => 'pages#projet'
  get '/calendrier', :to => 'pages#calendrier'
  get '/ged', :to => 'pages#ged'
  delete '/signout', :to => 'sessions#destroy'
  post "/projects/add_member", :to => 'projects#add_member'
  get "/projects/remove_member", :to => 'projects#remove_member'
  post "/tasks/add_member", :to => 'tasks#add_member'
  get "/tasks/remove_member", :to => 'tasks#remove_member'
  









end

app/views/layouts/_footer.html.erb
<!--Footer-->
<footer class="footer_wrapper" id="contact">
  <div class="container">
    <div class="footer_bottom"><span></span> </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--Header_section-->
<header id="header_wrapper">
  <div class="container">
    <div class="header_box">			  
		  <%= render 'layouts/menu' %>	  
    </div>
  </div>
</header>
<!--Header_section-->

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
       	
       	
       
	    <div id="main-nav" class="collapse navbar-collapse navStyle">
	    	<!--<div class="logo"><a href="#"><img src="/images/logo.png" alt="logo"></a></div>-->
	    	
			<ul class="nav navbar-nav" id="mainNav">
				<li class="menubtn"></li>	
				<li><%= link_to "Acceuil", root_path %></li>
				<li><%= link_to "Calendrier", calendrier_path %></li>	 			  				 			 
			    <li><%= link_to "Projet", projet_path %></li>	
			    <li><%= link_to "GED", ged_path %></li>	 
			    <% if current_user.admin? %>
				<li><%= link_to 'Contacts', following_user_path(current_user) %></li>
           	 	<% end %> 
			</ul>
				
			<nav style="float: right;">
		  	
			  	<ul class="nav navbar-nav" id="mainNav">
			  			<li><% if current_user.admin? %> <%= link_to "Configuration", administration_path %> <% end %></li>		        	      						
						<li><%= link_to current_user.contact.nom_complet, settings_user_path(current_user) %></li>
					<span style="position: absolute; top:30px; right: 100px;"><%= link_to "Déconnexion", signout_path, :id =>" lien_deconnexion", :method => :delete, :confirm => "Voulez-vous vraiment vous deconnecter ?" %></span>	
				</ul>	
				
				<div class="author-avatar"><a href="<%= settings_user_path(current_user) %>"><%= image_tag("team_pic2.jpg", :width => "50px", :height => "50px", :alt => "Team Member", :class => "img-circle") %></a></div>
			  	  	
		  </nav>
      </div>
       
</nav>

app/views/layouts/_side_menu.html.erb
    <div id="navbar">
      
      <!-- use captain icon for toggle menu -->
      <div id="hamburgermenu">
      	<ul id="leftNavigation">
						
						<% if current_user.admin? %>
			            <li>
			                <a href="#"><i class="fa leftNavIcon"></i> Administration</a>
			                <ul>
			                    <li>
			                    	<%= link_to 'Utilisateurs', users_path %>
			                    </li>
			                    <li>
			                    	<%= link_to 'Projets', projects_path %>
			                    </li>
			                    <li>
			                    	<%= link_to 'GED', datafiles_path %>
			                    </li>
			                </ul>
			            </li>
			            <% end %>
			            <li>
			                <a href="#"><i class="fa leftNavIcon"></i> Publication</a>
			                <ul>
			                    <li>
			                        <a href=" <%= feed_user_path(current_user) %> "><i class="fa fa-angle-right leftNavIcon"></i> Mes Publications</a>
			                    </li>                  
			                </ul>
			            </li>
			            <li>
			                <a href="#"><i class="fa leftNavIcon"></i> Messagerie</a>
			                <ul>
			                    <li>
			                        <a href="<%= messages_utilisateur_user_path(current_user) %>"><i class="fa fa-angle-right leftNavIcon"></i> Boite de reception</a>
			                    </li>
			                </ul>
			            </li>
			            <li>
			                <a href="#"><i class="fa leftNavIcon"></i> Contacts</a>
			                <ul>
			                	<li>
			                        <a href="#"><i class="fa fa-angle-right leftNavIcon"></i> Mes contacts</a>
			                    </li>
			                    
			                	<li>
			                        <a href="<%= following_user_path(current_user) %>"><i class="fa fa-angle-right leftNavIcon"></i> Mes abonnements</a>
			                    </li>
			                    <li>
			                        <a href="<%= followers_user_path(current_user) %>"><i class="fa fa-angle-right leftNavIcon"></i> Mes abonnés</a>
			                    </li>                  
			                </ul>
			            </li>
			            <li>
			                <a href="#"><i class="fa leftNavIcon"></i> Agenda</a>
			                <ul>
			                    <li>
			                    	<a href="<%= calendrier_path %>"><i class="fa fa-angle-right leftNavIcon"></i> Calendrier</a>
			                    </li>                    
			                </ul>
			                <ul>
			                    <li>
			                        <a href="<%= taches_attribuees_user_path(current_user) %>"><i class="fa fa-angle-right leftNavIcon"></i> Mes tâches</a>
			                    </li>                    
			                </ul>
			            </li>
			            
			           
			        </ul>
			        <div id="users_sidemenu" data-user ="<%= current_user.id %>">		        	
			           		
			           	<% unless @current_user.following == nil || @current_user.following.empty? %>			           		 		
			           		
			           		<% @cu_roster=@current_user.following%>
			           	 
			           	 	<%= render 'layouts/side_menu_users' %>
			           	 
			           	<% else %>
							<ul>
								<li><span>Aucun contact</span></li>
							</ul>
						
						<% end %>
						
						
							
					</div>

      </div>
    </div>
    <div class="overlay"></div>

app/views/layouts/_side_menu_users.html.erb
						            		
		            		<% if @clientxmpp != nil %>            		
		            		
							<ul>					        	
						        
						        <% @cu_roster.each do |user_roster| %>

							    		
							    			<li>  
							    					 						    					
							    				
							    				<a href="/contacts/<%= user_roster.contact.id %>">
							    					
							    					<span style ="float: right">
							    															    																	
																				        
														<% if user_roster.en_ligne?(@clientxmpp) %>
														
															<% if (user_roster.last_activity(@clientxmpp,current_user)!=nil) && (user_roster.last_activity(@clientxmpp,current_user) > 60)  %>
																	<%= time_ago_in_words(user_roster.last_activity(@clientxmpp,@current_user).seconds.ago) %>
															<% end %>
														
															<%= image_tag("online.png", :width => "10px", :height => "10px",:alt => "En ligne") %>
															
														<% else %>
														
															<%= time_ago_in_words(user_roster.derniere_connexion(true).seconds.ago) %>
										
														<% end %>
														
														
													</span>
							    					
						    					
							    					<span><%= user_roster.contact.nom_complet %></span>

							    					
							    					
							    					
							    					
							    				</a>
									
					
											</li>

							     <% end %> 	        	
								
								
							</ul>   
							
							<% else %>
							
							Connexion impossible au service de discussion instantané
							
							
							<% end %> 
							    
						
					

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
  <title> <%= @titre %> </title>
  
  <meta name="viewport" content="width=device-width, maximum-scale=1">
  
   <%= csrf_meta_tags %>
  
   <link rel="icon" href="favicon.png" type="image/png">	
    
    
    <%= stylesheet_link_tag 'sidebar.css' %>
    	
	<%= stylesheet_link_tag 'bootstrap.min.css' %>
	<%= stylesheet_link_tag 'style.css' %>
	<%= stylesheet_link_tag 'font-awesome.css' %>
	<%= stylesheet_link_tag 'animate.css' %>	
	<%= stylesheet_link_tag 'table.css' %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>	
	
	<%= javascript_include_tag 'application' %>	
	
	

 	<!--[if lt IE 9]>
	    <script src="js/respond-1.1.0.min.js"></script>
	    <script src="js/html5shiv.js"></script>
	    <script src="js/html5element.js"></script>
	<![endif]-->
 
</head>
<body>

<% if signed_in? %>
	
<%= render 'layouts/header' %> 

<%= render 'layouts/side_menu' %>

<% end %>

<div id="wrapper">

<%= yield %>

</div>

<%= render 'layouts/footer' %> 



<%= debug(params) if Rails.env.development? %>


	<%= javascript_include_tag 'bootstrap.min.js' %>
	<%= javascript_include_tag 'jquery-scrolltofixed.js' %>
	<%= javascript_include_tag 'jquery.nav.js' %>	
	<%= javascript_include_tag 'jquery.easing.1.3.js' %>
	<%= javascript_include_tag 'jquery.isotope.js' %>	
	<%= javascript_include_tag 'wow.js' %>
	<%= javascript_include_tag 'custom.js' %>
	<%= javascript_include_tag 'hamburger-menu.js' %> 
	<%= javascript_include_tag 'jquery.ssd-vertical-navigation.min.js' %>
	<%= javascript_include_tag 'sidebar.js' %>	
	

</body>
</html>